In [10]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/pleydier/Air_Passengers_Answer/master/Soumission%20Ramp/LightGBM/external_data.csv')

In [7]:
my_extern = pd.read_csv('submissions/submit/external_data.csv', index_col=0)

In [11]:
my_extern.head()

Date AirPort  Max TemperatureC  Mean TemperatureC  Min TemperatureC  \
0  2011-09-01     ATL                35                 29                24   
1  2011-09-02     ATL                36                 29                22   
2  2011-09-03     ATL                35                 29                23   
3  2011-09-04     ATL                27                 24                22   
4  2011-09-05     ATL                26                 24                22   

   Dew PointC  MeanDew PointC  Min DewpointC  Max Humidity  Mean Humidity  \
0          21              18             14            79             56   
1          17              15             14            61             46   
2          17              16             14            64             47   
3          22              19             16            93             72   
4          23              22             20            94             91   

   Min Humidity  Max Sea Level PressurehPa  Mean Sea Level PressurehPa  \
0            32                       1022                        1019   
1            30                       1019                        1016   
2            30                       1015                        1013   
3            51                       1014                        1012   
4            87                       1010                        1005   

   Min Sea Level PressurehPa  Max VisibilityKm  Mean VisibilityKm  \
0                       1017                16                 16   
1                       1014                16                 16   
2                       1011                16                 16   
3                       1011                16                 14   
4                        999                16                 13   

   Min VisibilitykM  Max Wind SpeedKm/h  Mean Wind SpeedKm/h  \
0                11                  19                    6   
1                16                  24                    7   
2                16                  19                    7   
3                 4                  21                    9   
4                 3                  32                   16   

   Max Gust SpeedKm/h  CloudCover  Events  WindDirDegrees  TOTAL_DEPARTURE  \
0                26.0           3     Sun             129          3582088   
1                34.0           2     Sun             185          3582088   
2                26.0           4     Sun             147          3582088   
3                26.0           6    Rain             139          3582088   
4                45.0           8  Extrem             149          3582088   

   TOTAL_DESTINATION  unemployment  INDEX_PRICE  Index_passengers  Price  \
0            3580851     10.995779     0.151846             115.0  85.52   
1            3580851     10.995779     0.151846             115.0  85.52   
2            3580851     10.995779     0.151846             115.0  85.52   
3            3580851     10.995779     0.151846             115.0  85.52   
4            3580851     10.995779     0.151846             115.0  85.52   

   Holiday  
0      0.0  
1      0.0  
2      1.0  
3      2.0  
4      3.0

In [12]:
data.head()

Date AirPort  Max TemperatureC  Mean TemperatureC  Min TemperatureC  \
0  2011-09-01     ATL                35                 29                24   
1  2011-09-02     ATL                36                 29                22   
2  2011-09-03     ATL                35                 29                23   
3  2011-09-04     ATL                27                 24                22   
4  2011-09-05     ATL                26                 24                22   

   Dew PointC  MeanDew PointC  Min DewpointC  Max Humidity  Mean Humidity  \
0          21              18             14            79             56   
1          17              15             14            61             46   
2          17              16             14            64             47   
3          22              19             16            93             72   
4          23              22             20            94             91   

   Min Humidity  Max Sea Level PressurehPa  Mean Sea Level PressurehPa  \
0            32                       1022                        1019   
1            30                       1019                        1016   
2            30                       1015                        1013   
3            51                       1014                        1012   
4            87                       1010                        1005   

   Min Sea Level PressurehPa  Max VisibilityKm  Mean VisibilityKm  \
0                       1017                16                 16   
1                       1014                16                 16   
2                       1011                16                 16   
3                       1011                16                 14   
4                        999                16                 13   

   Min VisibilitykM  Max Wind SpeedKm/h  Mean Wind SpeedKm/h  \
0                11                  19                    6   
1                16                  24                    7   
2                16                  19                    7   
3                 4                  21                    9   
4                 3                  32                   16   

   Max Gust SpeedKm/h Precipitationmm  CloudCover             Events  \
0                26.0            0.00           3                NaN   
1                34.0            0.00           2                NaN   
2                26.0            0.00           4                NaN   
3                26.0            6.10           6               Rain   
4                45.0           16.00           8  Rain-Thunderstorm   

   WindDirDegrees DateOfDeparture  is_weekend  is_holiday  \
0             129      2011-09-01       False       False   
1             185      2011-09-02       False       False   
2             147      2011-09-03        True       False   
3             139      2011-09-04        True       False   
4             149      2011-09-05       False        True   

   is_close_from_weekend_or_holiday     City    State  Unemployment_Rate  \
0                             False  Atlanta  Georgia                3.9   
1                              True  Atlanta  Georgia                3.9   
2                             False  Atlanta  Georgia                3.9   
3                             False  Atlanta  Georgia                3.9   
4                              True  Atlanta  Georgia                3.9   

   Peer_capita_income  Median_income  Average Wage  \
0               58756          49321         56350   
1               58756          49321         56350   
2               58756          49321         56350   
3               58756          49321         56350   
4               58756          49321         56350   

   Net_domestic_migration_rate_per_1000_hab  TFR 2018      lat        lon  \
0                                      3.98      1.79  33.6367 -84.428101   
1                                      3.98      1.79  33.6367 -84.428101   
2      

In [13]:
import problem

In [14]:
X,y = problem.get_train_data()

In [60]:
my_extern

Date AirPort  Max TemperatureC  Mean TemperatureC  \
0      2011-09-01     ATL                35                 29   
1      2011-09-02     ATL                36                 29   
2      2011-09-03     ATL                35                 29   
3      2011-09-04     ATL                27                 24   
4      2011-09-05     ATL                26                 24   
...           ...     ...               ...                ...   
11035  2013-03-01     LGA                 7                  5   
11036  2013-03-02     LGA                 4                  2   
11037  2013-03-03     LGA                 4                  2   
11038  2013-03-04     LGA                 5                  2   
11039  2013-03-05     LGA                 9                  5   

       Min TemperatureC  Dew PointC  MeanDew PointC  Min DewpointC  \
0                    24          21              18             14   
1                    22          17              15             14   
2                    23          17              16             14   
3                    22          22              19             16   
4                    22          23              22             20   
...                 ...         ...             ...            ...   
11035                 3          -1              -3             -4   
11036                 0          -2              -5             -6   
11037                -1          -5              -8             -9   
11038                -2          -7              -8             -9   
11039                 1          -3              -5             -7   

       Max Humidity  Mean Humidity  Min Humidity  Max Sea Level PressurehPa  \
0                79             56            32                       1022   
1                61             46            30                       1019   
2                64             47            30                       1015   
3                93             72            51                       1014   
4                94             91            87                       1010   
...             ...            ...           ...                        ...   
11035            76             63            49                       1008   
11036            82             65            48                       1008   
11037            69             55            40                       1008   
11038            63             54            44                       1012   
11039            61             49            37                       1016   

       Mean Sea Level PressurehPa  Min Sea Level PressurehPa  \
0                            1019                       1017   
1                            1016                       1014   
2                            1013                       1011   
3                            1012                       1011   
4                            1005                        999   
...                           ...                        ...   
11035                        1005                       1002   
11036                        1007                       1006   
11037                        1006                       1004   
11038                        1009                       1008   
11039                        1015                       1013   

       Max VisibilityKm  Mean VisibilityKm  Min VisibilitykM  \
0                    16                 16                11   
1                    16                 16                16   
2                    16                 16                16   
3                    16                 14                 4   
4                    16                 13                 3   
...                 ...                ...               ...   
11035                16                 16                16   
11036                16                 15                 6   
11037                16                 15                 8   
11038                

In [57]:
view = X.merge(data[["Net_domestic_migration_rate_per_1000_hab",
                     'city_population',"Median_income",'Date','AirPort']], how='left', 
        left_on=["DateOfDeparture", "Arrival"],
       right_on=["Date",'AirPort'])

In [59]:
np.corrcoef(y,view["Average Wage"])

array([[ 1.        , -0.01484184],
       [-0.01484184,  1.        ]])

In [66]:
extern_augmented = my_extern.merge(data[["Net_domestic_migration_rate_per_1000_hab",
                     'city_population',"Median_income",'Date','AirPort']], how='left', 
        on=["Date", "AirPort"])

In [67]:
extern_augmented.to_csv('extern.csv')

In [69]:
test = X.merge(extern_augmented, how='left', 
        left_on=["DateOfDeparture", "Arrival"],
       right_on=["Date",'AirPort'])

In [74]:
for i in test :
    try : 
        print(i)
        print(np.corrcoef(y,test[i]))
    except :
        pass

DateOfDeparture
Departure
Arrival
WeeksToDeparture
[[1.         0.16345274]
 [0.16345274 1.        ]]
std_wtd
[[1.         0.10923102]
 [0.10923102 1.        ]]
Date
AirPort
Max TemperatureC
[[1.         0.08275744]
 [0.08275744 1.        ]]
Mean TemperatureC
[[1.         0.09895804]
 [0.09895804 1.        ]]
Min TemperatureC
[[1.         0.11446138]
 [0.11446138 1.        ]]
Dew PointC
[[1.         0.14645041]
 [0.14645041 1.        ]]
MeanDew PointC
[[1.         0.14037778]
 [0.14037778 1.        ]]
Min DewpointC
[[1.         0.13219435]
 [0.13219435 1.        ]]
Max Humidity
[[1.         0.09061961]
 [0.09061961 1.        ]]
Mean Humidity
[[1.         0.08344611]
 [0.08344611 1.        ]]
Min Humidity
[[1.         0.06781617]
 [0.06781617 1.        ]]
Max Sea Level PressurehPa
[[ 1.         -0.05989081]
 [-0.05989081  1.        ]]
Mean Sea Level PressurehPa
[[ 1.       -0.037448]
 [-0.037448  1.      ]]
Min Sea Level PressurehPa
[[ 1.         -0.01431508]
 [-0.01431508  1.        ]]